name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  csharp:

    runs-on: ubuntu-latest
    env:
      working-directory: ./csharp

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}

  typescript:

    runs-on: ubuntu-latest
    env:
      working-directory: ts

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Test
      run: npm test
      working-directory: ${{env.working-directory}}
